language: python
matrix:
  include:
    - python: "3.4"
      env: TOXENV=py34
    - python: "3.5"
      env: TOXENV=py35
install:
  - "pip install -U pip wheel"
  - "pip install -r dev_requirements.txt"
  - "pip install ."
script:
  - tox