language: python
matrix:
  include:
    - python: "3.4"
      env: TOXENV=py34
    - python: "3.5"
      env: TOXENV=py35
before_install:
  - nvm install 6.5
  - nvm use 6.5
install:
  - "pip install -U pip wheel"
  - "pip install -r dev_requirements.txt"
  - "pip install ."
  - "npm install"
script:
  - tox
  - ./node_modules/.bin/karma start --single-run